// Code generated by autodoc-gen; DO NOT EDIT.
package autodoc

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// ─── Code Generation (Build-Time) ──────────────────────────────────────────

// CodeGen is a build-time generator that scans your router registration calls
// and generates a Go source file with embedded OpenAPI spec and route table.
//
// Usage:
//
//	go generate ./...
//
// In your code, add:
//
//	//go:generate autodoc-gen -router=chi -out=generated_docs.go -spec=openapi.json
//
// This will:
//  1. Parse all .go files in the package
//  2. Find chi.Router or http.ServeMux registrations
//  3. Extract route patterns, methods, and type hints
//  4. Generate a static route table + embedded OpenAPI spec
//  5. Emit generated_docs.go with zero runtime cost
type CodeGen struct {
	// RouterType is "chi" or "http"
	RouterType string
	// OutputFile is where to write generated code
	OutputFile string
	// SpecOutputFile is where to write the OpenAPI spec (optional, separate file)
	SpecOutputFile string
	// SpecYAMLOutputFile is where to write the OpenAPI spec as YAML (optional)
	SpecYAMLOutputFile string
	// PackageName is the target package name
	PackageName string
	// Paths to scan for router registration code
	ScanDirs []string
	// Config to use for the generated spec
	Config Config
	// modelSchemas stores pre-generated schemas for models specified by name
	modelSchemas map[string]map[string]interface{}
}

// Route represents a single discovered route at build time.
type Route struct {
	Method       string
	Path         string
	Summary      string
	Description  string
	OperationID  string
	RequestType  string // fully qualified type name, e.g., "github.com/example/api.CreateUserRequest"
	ResponseType string // fully qualified type name
	StatusCode   int
	Tags         []string
}

// NewCodeGen creates a new code generation engine.
func NewCodeGen(cfg Config, routerType string) *CodeGen {
	return &CodeGen{
		RouterType:   routerType,
		Config:       cfg,
		ScanDirs:     []string{"."},
		modelSchemas: make(map[string]map[string]interface{}),
	}
}

// Scan walks the filesystem and extracts route registrations.
func (cg *CodeGen) Scan() ([]Route, error) {
	var routes []Route

	for _, dir := range cg.ScanDirs {
		err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}

			fset := token.NewFileSet()
			node, err := parser.ParseFile(fset, path, nil, parser.AllErrors)
			if err != nil {
				// Skip files that don't parse; they may be incomplete
				return nil
			}

			ast.Inspect(node, func(n ast.Node) bool {
				routes = cg.extractRoutes(n, routes)
				return true
			})

			return nil
		})
		if err != nil {
			return nil, err
		}
	}

	// If models are specified as strings, resolve them to reflect.Type
	cg.resolveModelTypes()

	return routes, nil
}

// resolveModelTypes scans for model types and collects struct definitions
func (cg *CodeGen) resolveModelTypes() {
	// Collect all struct type names from scanned files
	for _, dir := range cg.ScanDirs {
		filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}

			fset := token.NewFileSet()
			node, err := parser.ParseFile(fset, path, nil, parser.AllErrors)
			if err != nil {
				return nil
			}

			ast.Inspect(node, func(n ast.Node) bool {
				if typeSpec, ok := n.(*ast.TypeSpec); ok {
					typeName := typeSpec.Name.Name
					// If this type is in our Models list, generate its schema
					for i, m := range cg.Config.Models {
						if name, ok := m.(string); ok && name == typeName {
							// Generate schema from AST
							if structType, ok := typeSpec.Type.(*ast.StructType); ok {
								schema := cg.buildSchemaFromAST(structType)
								// Add to the schemas map (will be done in Generate)
								cg.modelSchemas[typeName] = schema
								cg.Config.Models[i] = nil // Mark as handled
							}
						}
					}
				}
				return true
			})

			return nil
		})
	}

	// Clean up nil entries from Models
	var cleaned []interface{}
	for _, m := range cg.Config.Models {
		if m != nil {
			cleaned = append(cleaned, m)
		}
	}
	cg.Config.Models = cleaned
}

// extractRoutes finds route registration calls in the AST.
// Supports patterns like:
//   - chi: r.Get(), r.Post(), r.Route()
//   - http: mux.HandleFunc("GET /path", ...)
func (cg *CodeGen) extractRoutes(node ast.Node, routes []Route) []Route {
	if callExpr, ok := node.(*ast.CallExpr); ok {
		route := cg.parseRouteCall(callExpr)
		if route != nil {
			routes = append(routes, *route)
		}
	}
	return routes
}

// parseRouteCall extracts a Route from a function call expression.
func (cg *CodeGen) parseRouteCall(call *ast.CallExpr) *Route {
	// Get the function being called
	fn, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return nil
	}

	method := fn.Sel.Name

	switch cg.RouterType {
	case "chi":
		return cg.parseChiRoute(method, call)
	case "http":
		return cg.parseHTTPRoute(method, call)
	case "gin":
		return cg.parseGinRoute(method, call)
	}

	return nil
}

// parseChiRoute extracts routes from chi calls like r.Get("/path", handler).
//
// Supported chi patterns:
//   - r.Get("/path", handler)              → GET /path
//   - r.Post("/path", handler)             → POST /path
//   - r.Put("/path", handler)              → PUT /path
//   - r.Delete("/path", handler)           → DELETE /path
//   - r.Patch("/path", handler)            → PATCH /path
//   - r.Head("/path", handler)             → HEAD /path
//   - r.Options("/path", handler)          → OPTIONS /path
//   - r.Method("GET", "/path", handler)    → GET /path
//   - r.MethodFunc("GET", "/path", handler) → GET /path
//   - r.Handle("/path", handler)           → all methods /path
//   - r.HandleFunc("/path", handler)       → all methods /path
//   - r.Route("/prefix", ...)              → skipped (sub-router)
//   - r.Group(...)                         → skipped (middleware group)
//   - r.Mount("/path", subRouter)          → skipped (mount)
func (cg *CodeGen) parseChiRoute(method string, call *ast.CallExpr) *Route {
	switch method {
	case "Get", "Post", "Put", "Delete", "Patch", "Head", "Options":
		return cg.parseChiHTTPMethodRoute(method, call)
	case "Method", "MethodFunc":
		return cg.parseChiMethodRoute(call)
	case "Handle", "HandleFunc":
		return cg.parseChiCatchAllRoute(call)
	case "Route", "Group", "Mount":
		return nil // sub-routers/groups handled at runtime or separately
	default:
		return nil
	}
}

// parseChiHTTPMethodRoute handles r.Get("/path", handler), r.Post(...), etc.
func (cg *CodeGen) parseChiHTTPMethodRoute(httpMethod string, call *ast.CallExpr) *Route {
	if len(call.Args) < 2 {
		return nil
	}

	pathLit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || pathLit.Kind != token.STRING {
		return nil
	}

	path := strings.Trim(pathLit.Value, `"`)
	return &Route{
		Method:      strings.ToUpper(httpMethod),
		Path:        path,
		OperationID: buildOperationID(httpMethod, path),
		StatusCode:  200,
		Tags:        []string{extractTag(path)},
	}
}

// parseChiMethodRoute handles r.Method("GET", "/path", handler) and r.MethodFunc(...).
func (cg *CodeGen) parseChiMethodRoute(call *ast.CallExpr) *Route {
	if len(call.Args) < 3 {
		return nil
	}

	methodLit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || methodLit.Kind != token.STRING {
		return nil
	}
	pathLit, ok := call.Args[1].(*ast.BasicLit)
	if !ok || pathLit.Kind != token.STRING {
		return nil
	}

	httpMethod := strings.ToUpper(strings.Trim(methodLit.Value, `"`))
	path := strings.Trim(pathLit.Value, `"`)
	return &Route{
		Method:      httpMethod,
		Path:        path,
		OperationID: buildOperationID(httpMethod, path),
		StatusCode:  200,
		Tags:        []string{extractTag(path)},
	}
}

// parseChiCatchAllRoute handles r.Handle("/path", handler) and r.HandleFunc(...).
// These register a handler for all HTTP methods; we emit a GET entry by default.
func (cg *CodeGen) parseChiCatchAllRoute(call *ast.CallExpr) *Route {
	if len(call.Args) < 2 {
		return nil
	}

	pathLit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || pathLit.Kind != token.STRING {
		return nil
	}

	path := strings.Trim(pathLit.Value, `"`)
	return &Route{
		Method:      "GET",
		Path:        path,
		OperationID: buildOperationID("GET", path),
		StatusCode:  200,
		Tags:        []string{extractTag(path)},
	}
}

// parseHTTPRoute extracts routes from http.ServeMux calls like
// mux.HandleFunc("GET /path", handler)
func (cg *CodeGen) parseHTTPRoute(method string, call *ast.CallExpr) *Route {
	if method != "HandleFunc" && method != "Handle" {
		return nil
	}

	if len(call.Args) < 1 {
		return nil
	}

	// First arg is the pattern "GET /path"
	patternLit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || patternLit.Kind != token.STRING {
		return nil
	}

	pattern := strings.Trim(patternLit.Value, `"`)
	httpMethod, path := parsePattern(pattern)

	if httpMethod == "" {
		return nil
	}

	return &Route{
		Method:      httpMethod,
		Path:        toOASPath(path),
		OperationID: buildOperationID(httpMethod, path),
		StatusCode:  200,
		Tags:        []string{extractTag(path)},
	}
}

// parseGinRoute extracts routes from gin.Engine calls like r.GET("/path", handler), r.POST(...), etc.
// It converts Gin's :param syntax to OpenAPI's {param} format.
func (cg *CodeGen) parseGinRoute(method string, call *ast.CallExpr) *Route {
	// Gin methods are usually uppercase: GET, POST, etc.
	supportedMethods := map[string]bool{
		"GET": true, "POST": true, "PUT": true, "DELETE": true, "PATCH": true, "HEAD": true, "OPTIONS": true,
	}
	upperMethod := strings.ToUpper(method)
	if !supportedMethods[upperMethod] {
		return nil
	}
	if len(call.Args) < 2 {
		return nil
	}
	// First argument is the path pattern
	pathLit, ok := call.Args[0].(*ast.BasicLit)
	if !ok || pathLit.Kind != token.STRING {
		return nil
	}
	path := strings.Trim(pathLit.Value, `"`)
	// Convert :param to {param}
	path = convertGinPatternToOAS(path)
	return &Route{
		Method:      upperMethod,
		Path:        path,
		OperationID: buildOperationID(upperMethod, path),
		StatusCode:  200,
		Tags:        []string{extractTag(path)},
	}
}

// convertGinPatternToOAS converts Gin's :param syntax to OpenAPI's {param}.
func convertGinPatternToOAS(pattern string) string {
	var b strings.Builder
	for i := 0; i < len(pattern); {
		if pattern[i] == ':' {
			j := i + 1
			for j < len(pattern) && ((pattern[j] >= 'a' && pattern[j] <= 'z') || (pattern[j] >= 'A' && pattern[j] <= 'Z') || (pattern[j] >= '0' && pattern[j] <= '9') || pattern[j] == '_') {
				j++
			}
			b.WriteByte('{')
			b.WriteString(pattern[i+1 : j])
			b.WriteByte('}')
			i = j
		} else {
			b.WriteByte(pattern[i])
			i++
		}
	}
	return b.String()
}

// buildSchemaFromAST converts an AST struct type to a JSON schema map
func (cg *CodeGen) buildSchemaFromAST(structType *ast.StructType) map[string]interface{} {
	props := map[string]interface{}{}
	var required []string

	if structType.Fields == nil {
		return map[string]interface{}{
			"type":       "object",
			"properties": props,
		}
	}

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			continue // embedded or anonymous field
		}
		fieldName := field.Names[0].Name
		if !ast.IsExported(fieldName) {
			continue
		}

		// Get JSON tag
		jsonTag := "json"
		if field.Tag != nil {
			tagStr := field.Tag.Value
			if strings.Contains(tagStr, "json:") {
				start := strings.Index(tagStr, "json:")
				rest := tagStr[start+5:]
				end := strings.IndexAny(rest, ",`")
				if end > 0 {
					jsonTag = rest[:end]
				}
			}
		}
		// Handle "-" to skip
		if jsonTag == "-" {
			continue
		}
		// Handle omitempty
		omitempty := strings.Contains(jsonTag, "omitempty")
		name := jsonTag
		if idx := strings.Index(name, ","); idx > 0 {
			name = name[:idx]
		}
		if name == "" {
			name = fieldName
		}

		// Get field type schema
		fieldSchema := cg.astTypeToSchema(field.Type)

		// Required check (pointer or omitempty = optional)
		if !omitempty && field.Type.(*ast.StarExpr) == nil {
			required = append(required, name)
		}

		props[name] = fieldSchema
	}

	result := map[string]interface{}{
		"type":       "object",
		"properties": props,
	}
	if len(required) > 0 {
		result["required"] = required
	}
	return result
}

// astTypeToSchema converts an AST type expression to a JSON schema
func (cg *CodeGen) astTypeToSchema(expr ast.Expr) map[string]interface{} {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return map[string]interface{}{"type": "string"}
		case "int", "int8", "int16", "int32":
			return map[string]interface{}{"type": "integer", "format": "int32"}
		case "int64":
			return map[string]interface{}{"type": "integer", "format": "int64"}
		case "uint", "uint8", "uint16", "uint32":
			return map[string]interface{}{"type": "integer", "format": "int32", "minimum": 0}
		case "uint64":
			return map[string]interface{}{"type": "integer", "minimum": 0}
		case "float32":
			return map[string]interface{}{"type": "number", "format": "float"}
		case "float64":
			return map[string]interface{}{"type": "number", "format": "double"}
		case "bool":
			return map[string]interface{}{"type": "boolean"}
		case "byte":
			return map[string]interface{}{"type": "string", "format": "byte"}
		case "rune":
			return map[string]interface{}{"type": "string"}
		default:
			// Assume it's a reference to another type
			return map[string]interface{}{"$ref": "#/components/schemas/" + t.Name}
		}
	case *ast.StarExpr:
		// Pointer - make nullable
		schema := cg.astTypeToSchema(t.X)
		schema["nullable"] = true
		return schema
	case *ast.ArrayType:
		return map[string]interface{}{
			"type":  "array",
			"items": cg.astTypeToSchema(t.Elt),
		}
	case *ast.MapType:
		return map[string]interface{}{
			"type":                 "object",
			"additionalProperties": cg.astTypeToSchema(t.Value),
		}
	case *ast.StructType:
		return cg.buildSchemaFromAST(t)
	default:
		return map[string]interface{}{}
	}
}

// Generate writes the generated Go code to OutputFile.
func (cg *CodeGen) Generate(routes []Route) error {
	// Build the OpenAPI spec from routes
	doc := New(cg.Config)
	for _, r := range routes {
		doc.Register(r.Method+" "+r.Path,
			WithSummary(r.Summary),
			WithOperationID(r.OperationID),
			WithTags(r.Tags...),
			WithStatusCode(r.StatusCode),
		)
	}

	specJSON, err := doc.SpecJSON()
	if err != nil {
		return fmt.Errorf("failed to generate spec: %w", err)
	}

	// If we have pre-built model schemas, inject them into the spec
	if len(cg.modelSchemas) > 0 {
		var spec map[string]interface{}
		if err := json.Unmarshal(specJSON, &spec); err != nil {
			return fmt.Errorf("failed to parse spec: %w", err)
		}

		components, ok := spec["components"].(map[string]interface{})
		if !ok {
			components = map[string]interface{}{}
			spec["components"] = components
		}
		schemas, ok := components["schemas"].(map[string]interface{})
		if !ok {
			schemas = map[string]interface{}{}
			components["schemas"] = schemas
		}

		for name, schema := range cg.modelSchemas {
			schemas[name] = schema
		}

		specJSON, err = json.MarshalIndent(spec, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to re-marshal spec: %w", err)
		}
	}

	// Write the spec to a separate file if requested
	if cg.SpecOutputFile != "" {
		if err := os.WriteFile(cg.SpecOutputFile, specJSON, 0644); err != nil {
			return fmt.Errorf("failed to write spec file: %w", err)
		}
	}

	// Write the spec as YAML if requested
	if cg.SpecYAMLOutputFile != "" {
		specYAML, err := doc.SpecYAML()
		if err != nil {
			return fmt.Errorf("failed to generate YAML spec: %w", err)
		}
		if err := os.WriteFile(cg.SpecYAMLOutputFile, specYAML, 0644); err != nil {
			return fmt.Errorf("failed to write YAML spec file: %w", err)
		}
	}

	// Embed the spec as a string in the generated Go code
	specStr := string(specJSON)
	escapedSpec := strings.ReplaceAll(specStr, `"`, `\"`)
	escapedSpec = strings.ReplaceAll(escapedSpec, "\n", `\n`)

	code := fmt.Sprintf(`// Code generated by autodoc-gen; DO NOT EDIT.
package %s

import (
	"encoding/json"
)

// generatedOpenAPISpec is the embedded OpenAPI 3.0 specification.
// Generated at build time from router registration code.
const generatedOpenAPISpec = "%s"

// GetOpenAPISpec returns the embedded OpenAPI specification.
func GetOpenAPISpec() map[string]interface{} {
	var spec map[string]interface{}
	if err := json.Unmarshal([]byte(generatedOpenAPISpec), &spec); err != nil {
		panic(err)
	}
	return spec
}

// StaticRoutes is a pre-computed route table for fast lookup at runtime.
var StaticRoutes = []struct {
	Method string
	Path   string
}{
`, cg.PackageName, escapedSpec)

	// Add route entries
	for _, r := range routes {
		code += fmt.Sprintf("\t{Method: %q, Path: %q},\n", r.Method, r.Path)
	}

	code += `}
`

	// Write the generated file
	if err := os.WriteFile(cg.OutputFile, []byte(code), 0644); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}

	log.Printf("Generated %s with %d routes", cg.OutputFile, len(routes))
	return nil
}

// GenerateAll is a convenience method that scans and generates in one call.
func (cg *CodeGen) GenerateAll() error {
	routes, err := cg.Scan()
	if err != nil {
		return err
	}
	return cg.Generate(routes)
}

// ─── Helper functions ─────────────────────────────────────────────────────────

func extractTag(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "/"), "/")
	if len(parts) == 0 || parts[0] == "" {
		return "default"
	}
	seg := parts[0]
	// Skip versioning segments like v1, v2, api
	if seg == "api" || isVersionSegment(seg) {
		if len(parts) > 1 && parts[1] != "" {
			seg = parts[1]
		}
	}
	return seg
}

func isVersionSegment(s string) bool {
	if len(s) < 2 || s[0] != 'v' {
		return false
	}
	for _, c := range s[1:] {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}
